#!/bin/bash

while [ "$1" != '' ]
do
  target=$1
  filename=`basename "$1"`
  image="${TMPDIR}${filename}.png"
  rsrc="${TMPDIR}icn.rsrc"

  # Create a thumbnail from the file preview
  qlmanage -t -i -s 1024 -o ${TMPDIR} "$target" $> /dev/null

  # apply the image to itself as an thumbnail icon
	fileicon set "$target" "$image"
  
  # clean up
	rm "$image"
  shift
done
